version: '3'

services:
  web:
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_WS_HOST=localhost
      - VITE_WS_PORT=8080
    ports:
      - 80:80
    networks:
      - mynet

  api-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=8080
    networks:
      - mynet
    ports:
      - 8080:8080

  stream-receiver:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - WS_HOST=api-server
      - WS_PORT=8080
    networks:
      - mynet
    depends_on:
      - api-server
    command: python3 -m app.stream_receiver

networks:
  mynet:
